name: SuspiciusCosmic
version: '${version}'
main: com.cosmicraft.suspiciuscosmic.SuspiciusCosmic
api-version: '1.20'

commands:
  sospechoso:
    description: "Revisa la inactividad de un jugador (cuánto se ha movido desde su punto de referencia)"
    usage: "/sospechoso [jugador]"
    permission: suspiciuscosmic.admin
    permission-message: "No tienes permiso para usar este comando."
  suspiciuscosmic:
    description: "Comandos del plugin (recargar, etc)"
    aliases: [sc]
    permission: suspiciuscosmic.admin
    permission-message: "No tienes permiso para usar este comando."

permissions:
  suspiciuscosmic.admin:
    description: "Permite comandos de admin"
    default: op